#!/usr/bin/env bash

###########################################################################################
# constants

# terminal default settings
STTY_ORIG=$(stty -g)

# ifs
IFS= # set ifs to null

# color constants
COL_L_TANK=$'\x1b[38;5;21m'
COL_R_TANK=$'\x1b[38;5;1m'
COL_OBSTACLE=$'\x1b[38;5;34m'
BB_ON_W=$'\x1b[1;38;5;0;48;5;15m'
COL_PROJECTILE=$'\x1b[38;5;196m'
COL_TRAIL1=$'\x1b[38;5;208m'
COL_TRAIL2=$'\x1b[38;5;220m'
COL_TRAIL3=$'\x1b[38;5;226m'
COL_EXPLOSION=$'\x1b[38;5;226m'
COL_HIDDEN_EXPLOSION=$'\x1b[38;5;0m\e[48;5;0m'
COL_NONE=$(tput sgr0)

read -r -d '' TUTORIAL <<-EOF
The objective is to destroy the enemy tank.
 
Controls:
    Move Tank:       'a' or Left Arrow (move left)
                     'd' or Right Arrow (move right)
    Adjust Angle:    'w' or Up Arrow (increase angle)
                     's' or Down Arrow (decrease angle)
    Adjust Power:    'm' (increase power)
                     'l' (decrease power)
    Fire Projectile: 'f' or Spacebar
    Quit Game:       'q'
EOF

# left tank
read -r -d '' L_TANK <<-"EOF"
     __
   _|__|_//
__/_______\__
\O_O_O_O_O_O/
EOF
L_TANK=$COL_L_TANK$L_TANK$COL_NONE

# right tank
read -r -d '' R_TANK <<-"EOF"
      __
  \\_|__|_
__/_______\__
\O_O_O_O_O_O/
EOF
R_TANK=$COL_R_TANK$R_TANK$COL_NONE

# tank dimensions
TANK_LEN=13
TANK_HEIGHT=4

# explosion frames
read -r -d '' FRAME0 <<-"EOF"
⋅
EOF
FRAME0=$COL_EXPLOSION$FRAME0$COL_NONE

read -r -d '' FRAME1 <<-"EOF"
⋅⋅⋅
⋅⋅⋅
⋅⋅⋅
EOF

FRAME1=$COL_EXPLOSION$FRAME1$COL_NONE

read -r -d '' FRAME2 <<-"EOF"
⋅⋅⋅⋅⋅
⋅⋅⋅⋅⋅
⋅⋅⋅⋅⋅
⋅⋅⋅⋅⋅
⋅⋅⋅⋅⋅
EOF
H_FRAME=$FRAME2
FRAME2=$COL_EXPLOSION$FRAME2$COL_NONE
H_FRAME=$COL_HIDDEN_EXPLOSION$H_FRAME$COL_NONE

EX_ARR=("$FRAME0"
    "$FRAME1"
    "$FRAME2"
)

# obstacle character
OBSTACLE="${COL_OBSTACLE}X$COL_NONE"

# projectile characters
BULLET="${COL_PROJECTILE}@$COL_NONE"
TRAIL1="${COL_TRAIL1}*$COL_NONE"
TRAIL2="${COL_TRAIL2}*$COL_NONE"
TRAIL3="${COL_TRAIL3}*$COL_NONE"

# obstacle density settings
MAX_DENS=1
MED_DENS=25
MIN_DENS=50

# angle constants
PI=$(echo "scale=10; 4*a(1)" | bc -l)

# gravity
GRAVITY=30

# power constants (initial projectile velocity)
MAX_POWER=110
MIN_POWER=20

MAX_ANGLE=180
MIN_ANGLE=0

TIME_LEN=300
DELTA=0.025

declare -a TIME_ARR

for ((k = 0; k <= TIME_LEN; k++)); do
    TIME_ARR[k]+=$(bc -l <<<"$k*$DELTA")
done
