#!/usr/bin/env bash

###########################################################################################
# constants

# terminal default settings
STTY_ORIG=$(stty -g)

# ifs
IFS= # set ifs to null

# color constants
COL_L_TANK=$'\x1b[38;5;28m'
COL_R_TANK=$'\x1b[38;5;124m'
COL_OBSTACLE=$'\x1b[38;5;44m'
BB_ON_W=$'\x1b[1;38;5;0;48;5;15m'
COL_PROJECTILE=$'\x1b[38;5;196m'
COL_TRAIL1=$'\x1b[38;5;208m'
COL_TRAIL2=$'\x1b[38;5;220m'
COL_TRAIL3=$'\x1b[38;5;226m'
COL_NONE=$(tput sgr0)

# left tank
read -r -d '' L_TANK <<-"EOF"
     __
   _|__|_//
__/_______\__
\O_O_O_O_O_O/
EOF
L_TANK=$COL_L_TANK$L_TANK$COL_NONE

# right tank
read -r -d '' R_TANK <<-"EOF"
      __
  \\_|__|_
__/_______\__
\O_O_O_O_O_O/
EOF
R_TANK=$COL_R_TANK$R_TANK$COL_NONE

# explosion frames

read -r -d '' FRAME0 <<-"EOF"
 ⋅
⋅⋅⋅
 ⋅
EOF
FRAME0=$COL_R_TANK$FRAME0$COL_NONE

read -r -d '' FRAME1 <<-"EOF"
 ⋅
⋅⋅⋅
 ⋅
EOF
FRAME1=$COL_R_TANK$FRAME1$COL_NONE

read -r -d '' FRAME2 <<-"EOF"
 ⋅⋅
⋅⋅⋅⋅
 ⋅⋅
EOF
FRAME2=$COL_R_TANK$FRAME2$COL_NONE

read -r -d '' FRAME3 <<-"EOF"
 ⋅⋅⋅
⋅⋅⋅⋅⋅
 ⋅⋅⋅
EOF
FRAME3=$COL_R_TANK$FRAME3$COL_NONE

# obstacle character
OBSTACLE="${COL_OBSTACLE}X$COL_NONE"

# projectile characters
BULLET="${COL_PROJECTILE}@$COL_NONE"
TRAIL1="${COL_TRAIL1}*$COL_NONE"
TRAIL2="${COL_TRAIL2}*$COL_NONE"
TRAIL3="${COL_TRAIL3}*$COL_NONE"

# power constants (initial projectile velocity)
MAX_POWER=100
MIN_POWER=20

